### ISSUE TITLE
Ingress crashes under some circumstances

### ISSUE THREAD

**Issue by margau** [Freifunk-IoT/ingress#9]
Traceback (most recent call last):
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/root/data-sink/mqtt.py", line 73, in <module>
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     client.loop_forever()
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1481, in loop_forever
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     rc = self.loop(timeout, max_packets)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1003, in loop
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     rc = self.loop_read(max_packets)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1284, in loop_read
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     rc = self._packet_read()
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1849, in _packet_read
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     rc = self._packet_handle()
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2305, in _packet_handle
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     return self._handle_publish()
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2500, in _handle_publish
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     self._handle_on_message(message)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2642, in _handle_on_message
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     callback(self, self._userdata, message)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/root/data-sink/mqtt.py", line 61, in on_message
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     db.store_point(dp)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/root/data-sink/database.py", line 31, in store_point
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     self.client.write_points([_datapoint_to_influx(datapoint)])
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 468, in write_points
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     tags=tags, protocol=protocol)
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 532, in _write_points
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     protocol=protocol
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 312, in write
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     headers=headers
Jul 23 19:34:20 ffs-iot-playground python3[12331]:   File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 271, in request
Jul 23 19:34:20 ffs-iot-playground python3[12331]:     raise InfluxDBClientError(response.content, response.status_code)
Jul 23 19:34:20 ffs-iot-playground python3[12331]: influxdb.exceptions.InfluxDBClientError: 400: {"error":"field type conflict: input field \"activePower\" on measurement \"Eagl
Jul 23 19:34:20 ffs-iot-playground systemd[1]: ffiot-ingress-mqtt.service: Main process exited, code=exited, status=1/FAILURE

**Comment by margau** [comment]
Solution would be: Proper Exception Handling for InfluxDB
